version: "3.8"

networks:
  btb-network:
    driver: bridge

services:
  # 예시: 웹 애플리케이션 서비스 추가
  house-app:
    build: .
    #image: gkstnaosi/contiroom
    container_name: contiroom
    ports:
      - "8080:8080"
    networks:
      - btb-network
    restart: always


