version: "3.8"

networks:
  house-network:
    driver: bridge

services:
  # 예시: 웹 애플리케이션 서비스 추가
  house-app:
    build: ./zip-go
    image: gkstnaosi/zip-go:latest
    container_name: zip-go
    ports:
      - "8080:8080"
    networks:
      - house-network
    restart: always

