
spring:
  application:
    name: continuous_room
  security:
    user:
      name: swagger
      password: qwer1234
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}