name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker Login 단계 추가
      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # SSH로 EC2 인스턴스에 접속하여 배포
      - name: SSH to EC2 and deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Docker Compose 설치
            sudo apt-get update
            sudo apt-get install -y docker-compose

            # Docker에서 이전 컨테이너가 실행 중이라면 중지하고 제거
            CONTAINER_ID=$(docker ps -q --filter "name=zip-go")
            if [ ! -z "$CONTAINER_ID" ]; then
              docker stop $CONTAINER_ID
              docker rm $CONTAINER_ID
            fi

            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKER_USERNAME }}/zip-go:${{ github.sha }}

            # Docker Compose로 새로운 컨테이너 실행
            docker-compose down
            docker-compose up -d

