name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Docker Login
      - name: Docker Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # Step 3: SSH to EC2 and deploy with Docker Compose
      - name: SSH to EC2 and deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Docker Compose 설치 (필요시)
            sudo apt-get update
            sudo apt-get install -y docker-compose

            # 이전 Docker 컨테이너 중지 및 제거
            CONTAINER_ID=$(docker ps -q --filter "name=zip-go")
            if [ ! -z "$CONTAINER_ID" ]; then
              docker stop $CONTAINER_ID
              docker rm $CONTAINER_ID
            fi

            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/zip-go:${{ github.sha }}

            # Docker Compose로 새로운 컨테이너 실행
            docker-compose down
            docker-compose up -d
