name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Docker Login
      - name: Docker Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # Step 3: SSH to EC2 and deploy with Docker Compose
      - name: SSH to EC2 and deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            docker-compose stop
            docker-compose rm -f
            docker rmi gkstnaosi/zip-go:latest
            docker-compose up -d
