name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 CI/CD 실행
  pull_request:
    branches:
      - main  # main 브랜치에 대한 PR이 생성될 때마다 CI/CD 실행

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 리포지토리 코드를 체크아웃

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give gradlew execute permission
        run: chmod +x ./gradlew  # gradlew에 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build  # Gradle로 프로젝트 빌드

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # GitHub Secrets에서 Docker Hub 사용자명 가져오기
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  # GitHub Secrets에서 Docker Hub 액세스 토큰 가져오기

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/contiroom:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/contiroom:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push  # build_and_push job이 성공적으로 완료된 후에 실행

    steps:
      # application.yaml 파일 생성 및 설정
      - name: Set application properties
        run: |
          echo "datasource:" > ./src/main/resources/application.yaml
          echo "  driver-class-name: com.mysql.cj.jdbc.Driver" >> ./src/main/resources/application.yaml
          echo "  url: ${ { secrets.DB_URL } }" >> ./src/main/resources/application.yaml
          echo "  username: ${ { secrets.DB_USERNAME } }" >> ./src/main/resources/application.yaml
          echo "  password: ${ { secrets.DB_PASSWORD } }" >> ./src/main/resources/application.yaml

      # 확인용 출력 (선택사항)
      - name: Display application.yaml content
        run: cat ./src/main/resources/application.yaml

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd zip-go
            docker-compose stop
            docker-compose rm -f
            docker rmi gkstnoasi/contiroom:latest
            docker pull gkstnaosi/contiroom:latest
            docker-compose up -d
